### ISSUE TITLE
Error when launching game

### ISSUE THREAD

**Issue by helloiamarfy** [goaaats/FFXIVQuickLauncher#102]
When I attempt to run the game I continue to get this error, I've tried running the game as an admin and I've deleted and rerun the program as well as adding the entire appdata file path as an antivirus exception and it continues to throw this at me. The hooks folder has the Dalamud.dll file as well as a download.zip that when attempting to extract gives me an access denied error and refuses to extract Dalamud.Injector.exe but pulls everything else out, so I'm not entirely sure what I'm doing wrong here.

```
System.UnauthorizedAccessException: Access to the path 'C:\Users\Nicole\AppData\Roaming\XIVLauncher\addon\Hooks\Dalamud.Injector.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at XIVLauncher.Addon.HooksAddon.Download(String addonPath, String ingamePluginPath) in E:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Addon\Implementations\HooksAddon.cs:line 158
   at XIVLauncher.Addon.HooksAddon.Run() in E:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Addon\Implementations\HooksAddon.cs:line 69
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.MainWindow.<StartGame>d__14.MoveNext() in E:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 429
3.6.0.0
3051009
Context: Hooks
Microsoft Windows NT 6.2.9200.0
True
True
True
False
False
English


[
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": true,
    "Addon": {
      "$type": "XIVLauncher.Addon.RichPresenceAddon, XIVLauncher",
      "Name": "FFXIV Discord Rich Presence"
    }
  }
]

```

**Comment by helloiamarfy** [comment]
ugh apparently my av had quarantined the exe after i restored it and added the exception, it wasn't showing under the quarantine right away. seems to be working now
