### ISSUE TITLE
Launcher flags this error

### ISSUE THREAD

**Issue by dfgfffffff** [goaaats/FFXIVQuickLauncher#103]
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not find file 'F:\common\common\FINAL FANTASY XIV Online\boot\ffxivboot64.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at XIVLauncher.Game.XivGame.GetFileHash(String file) in E:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 399
   at XIVLauncher.Game.XivGame.GetBootVersionHash() in E:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 250
   at XIVLauncher.Game.XivGame.RegisterSession(OauthLoginResult loginResult) in E:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 275
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Game.XivGame.Login(String userName, String password, String otp, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, Boolean useCache) in E:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 85
   at XIVLauncher.Windows.MainWindow.<StartGame>d__14.MoveNext() in E:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 400
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not find file 'F:\common\common\FINAL FANTASY XIV Online\boot\ffxivboot64.exe'.
File name: 'F:\common\common\FINAL FANTASY XIV Online\boot\ffxivboot64.exe'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at XIVLauncher.Game.XivGame.GetFileHash(String file) in E:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 399
   at XIVLauncher.Game.XivGame.GetBootVersionHash() in E:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 250
   at XIVLauncher.Game.XivGame.RegisterSession(OauthLoginResult loginResult) in E:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 275
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

3.6.0.0
3051009
Context: Login
Microsoft Windows NT 6.2.9200.0
True
True
False
False
False
English

[
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": true,
    "Addon": {
      "$type": "XIVLauncher.Addon.RichPresenceAddon, XIVLauncher",
      "Name": "FFXIV Discord Rich Presence"
    }
  }
]

**Comment by goaaats** [comment]
Is your game updated? If you run XIVLauncher with an initial installation, this might happen - I'll add a check for it.

**Comment by dfgfffffff** [comment]
Game is updated to current patch.

**Comment by goaaats** [comment]
Not really - could you take a screenshot of F:\common\common\FINAL FANTASY XIV Online\ and F:\common\common\FINAL FANTASY XIV Online\boot? Is F a Network Drive?

**Comment by goaaats** [comment]
No response from owner, closing
