### ISSUE TITLE
error since the last patch

### ISSUE THREAD

**Issue by sisco1986** [goaaats/FFXIVQuickLauncher#109]
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at XIVLauncher.Dalamud.DalamudLauncher.Run() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 117
   at XIVLauncher.Windows.MainWindow.<StartGame>d__14.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 462
4.0.0.0
ab34bc3
Context: Hooks
Microsoft Windows NT 6.2.9200.0
True
True
True
True
False
English

[
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": true,
    "Addon": {
      "$type": "XIVLauncher.Addon.RichPresenceAddon, XIVLauncher",
      "Name": "FFXIV Discord Rich Presence"
    }
  },
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": true,
    "Addon": {
      "$type": "XIVLauncher.Addon.GenericAddon, XIVLauncher",
      "Path": "E:\\Advanced Combat Tracker\\Advanced Combat Tracker.exe",
      "CommandLine": "",
      "RunAsAdmin": false,
      "KillAfterClose": true,
      "Name": "Launch EXE : Advanced Combat Tracker"
    }
  }
]

**Comment by nommi** [comment]
I have error since newest patch as well, this is my error message, kind of similar to error above.

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.String.StartsWith(String value)
   at XIVLauncher.Dalamud.DalamudLauncher.Run() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 76
   at XIVLauncher.Windows.MainWindow.<StartGame>d__14.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 462
4.0.0.0
ab34bc3
Context: Hooks
Microsoft Windows NT 6.2.9200.0
True
True
True
True
False
English


[
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": false,
    "Addon": {
      "$type": "XIVLauncher.Addon.RichPresenceAddon, XIVLauncher",
      "Name": "FFXIV Discord Rich Presence"
    }
  }
]

**Comment by goaaats** [comment]
Please try to delete the folder %AppData\XIVLauncher\addon\Hooks and check again. Sorry, will be fixed with the next launcher patch!

**Comment by Aida-Enna** [comment]
Assumed to be fixed in latest patch due to lack of activity - If this is still an issue, please comment here or open a new issue. Thank you!
