### ISSUE TITLE
installeed my bit deffender last night, iim assumnig is what caused this?

### ISSUE THREAD

**Issue by HawtSTuff1337** [goaaats/FFXIVQuickLauncher#117]
System.UnauthorizedAccessException: Access to the path 'C:\Users\jordo\AppData\Roaming\XIVLauncher\addon\Hooks\Dalamud.Injector.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at XIVLauncher.Dalamud.DalamudLauncher.Download(String addonPath, String ingamePluginPath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 179
   at XIVLauncher.Dalamud.DalamudLauncher.Run() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 85
   at XIVLauncher.Windows.MainWindow.<StartGame>d__14.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 462
4.0.0.0
ab34bc3
Context: Hooks
Microsoft Windows NT 6.2.9200.0
True
True
True
True
False
English

[
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": true,
    "Addon": {
      "$type": "XIVLauncher.Addon.RichPresenceAddon, XIVLauncher",
      "Name": "FFXIV Discord Rich Presence"
    }
  },
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": true,
    "Addon": {
      "$type": "XIVLauncher.Addon.GenericAddon, XIVLauncher",
      "Path": "C:\\Users\\jordo\\Documents\\ACTv3\\Advanced Combat Tracker.exe",
      "CommandLine": "",
      "RunAsAdmin": true,
      "KillAfterClose": false,
      "Name": "Launch EXE : Advanced Combat Tracker"
    }
  },
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": true,
    "Addon": {
      "$type": "XIVLauncher.Addon.GenericAddon, XIVLauncher",
      "Path": "C:\\Windows.old\\Users\\jordo\\AppData\\Local\\XIVHunt\\XIV-Hunt.exe",
      "CommandLine": "",
      "RunAsAdmin": true,
      "KillAfterClose": false,
      "Name": "Launch EXE : XIV-Hunt"
    }
  },
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": true,
    "Addon": {
      "$type": "XIVLauncher.Addon.GenericAddon, XIVLauncher",
      "Path": "C:\\Windows.old\\Users\\jordo\\AppData\\Local\\Discord\\Update.exe",
      "CommandLine": "",
      "RunAsAdmin": true,
      "KillAfterClose": false,
      "Name": "Launch EXE : Update"
    }
  },
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": true,
    "Addon": {
      "$type": "XIVLauncher.Addon.GenericAddon, XIVLauncher",
      "Path": "C:\\Users\\jordo\\Documents\\Miqobot\\miqobot_v1.3.29.exe",
      "CommandLine": "",
      "RunAsAdmin": true,
      "KillAfterClose": false,
      "Name": "Launch EXE : miqobot_v1.3.29"
    }
  }
]

**Comment by goaaats** [comment]
Yeah, seems like it, please try to add exclusions to it for that folder

**Comment by goaaats** [comment]
Closing as no response from owner
