### ISSUE TITLE
No fitting error message for boot version conflict

### ISSUE THREAD

**Issue by blckshdw** [goaaats/FFXIVQuickLauncher#118]
System.AggregateException: One or more errors occurred. ---> System.Exception: Cannot verify Game version, Boot is outdated.
   at XIVLauncher.Game.XivGame.RegisterSession(OauthLoginResult loginResult)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Game.XivGame.Login(String userName, String password, String otp, Boolean isSteamServiceAccount, Boolean useCache)
   at XIVLauncher.Windows.MainWindow.<StartGame>d__14.MoveNext()
---> (Inner Exception #0) System.Exception: Cannot verify Game version, Boot is outdated.
   at XIVLauncher.Game.XivGame.RegisterSession(OauthLoginResult loginResult)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

4.1.0.0
89ca295-dirty
Context: Login
Microsoft Windows NT 6.2.9200.0
True
True
False
True
False
English

[]

**Comment by Zyian** [comment]
Sounds like you need to run the original launcher first to get all of the updates. If the boot executable has an update it needs to get updated first so that quick launch can get to it

**Comment by goaaats** [comment]
Exactly, I'll add a better error message for this

**Comment by goaaats** [comment]
Boot patch error is now handled in the same way as game patch as of https://github.com/goaaats/FFXIVQuickLauncher/commit/d736a6c2c33a17e7853ec064746b8aa45bb5e9c2
