### ISSUE TITLE
After recent update launcher no longer works

### ISSUE THREAD

**Issue by Jhazor** [goaaats/FFXIVQuickLauncher#131]
System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Game.AdminCheck.RunCheck()
   at XIVLauncher.Windows.MainWindow.InitializeWindow()
   at XIVLauncher.Windows.MainWindow.AutoUpdaterOnCheckForUpdateEvent(UpdateInfoEventArgs args)
   at AutoUpdaterDotNET.AutoUpdater.BackgroundWorkerOnRunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs runWorkerCompletedEventArgs) in c:\projects\AutoUpdater.NET\AutoUpdater.NET\AutoUpdater.cs:line 268
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at XIVLauncher.App.Main()
4.3.0.0
88776f4
Context: Unhandled
Microsoft Windows NT 6.2.9200.0
True
True
True
False
False
English

[
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": true,
    "Addon": {
      "$type": "XIVLauncher.Addon.RichPresenceAddon, XIVLauncher",
      "Name": "FFXIV Discord Rich Presence"
    }
  },
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": true,
    "Addon": {
      "$type": "XIVLauncher.Addon.GenericAddon, XIVLauncher",
      "Path": "D:\\Actor\\ACT\\Advanced Combat Tracker.exe",
      "CommandLine": "",
      "RunAsAdmin": true,
      "KillAfterClose": false,
      "Name": "Launch EXE : Advanced Combat Tracker"
    }
  }
]

**Comment by ff-meli** [comment]
Same issue reported by Neh in discord.

Might be worth including the pdb in the install for line numbers, unless you get them with sentry.

**Comment by jchrisrogers** [comment]
Tried deleting the folder `%AppData%\XIVLauncher\addon\Hook` (as well as the the XIVLauncher folder in `%AppData%`) and the same error appears as above.

**Comment by goaaats** [comment]
Will be fixed later today!

**Comment by jchrisrogers** [comment]
Here is a workaround until @goaaats is able to fix the issue:

1) Go to the install folder for XIVLauncher
2) Right click on the the file XIVLauncher.exe and select Properties
3) Click the Compatibility tab and check the box for Run this program as an administrator under the Settings section
4) Click Apply and then Ok
5) Run the XIVLauncher program. You will see the dialog box in the screenshot (below) after allowing the program to run
6) In the dialog box, click OK. XIVLauncher should continue to run without elevated privileges
![image](https://user-images.githubusercontent.com/19679596/71536337-8999f400-28d3-11ea-978d-bcf6948e7497.png)

**Comment by goaaats** [comment]
Should be fixed in 4.4.0.0
