### ISSUE TITLE
4.4 Update erased all settings.

### ISSUE THREAD

**Issue by Drakonas** [goaaats/FFXIVQuickLauncher#134]
XIVLauncher auto-updated to the latest version and all my settings for bot tokens/channels were reset, and the initial setup wizard started when the program launched after the update. I don't think this is intended, and it's a bit annoying because I can't remember what bot I used for the token.

**Comment by ff-meli** [comment]
While it does start the setup wizard and erase your preferences (for things like game path, user accounts, whether to enable in-game features), all bot settings and config are entirely separate and in a file that was not touched by the update process.  If you look in C:\Users\<you>\AppData\Roaming\XivLauncher, there should be a file called dalamudConfig.json.  That will have all your bot config info.

The update process doesn't touch that file (or folder) at all - the wizard issue is due to files in a different place that windows recreated.

**Comment by goaaats** [comment]
Sorry about this, it's caused by changing my build environment. I'll migrate to another solution for storing settings so this doesn't happen anymore.

**Comment by Drakonas** [comment]
I apologize. It seems this happened long ago.

2019-10-26 11:03:39.824 -04:00 [INF] Nhaama game data update failed.
System.ComponentModel.Win32Exception (0x80004005): Only part of a ReadProcessMemory or WriteProcessMemory request was completed
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Nhaama.FFXIV.Actor.ActorTableCollection.Update() in E:\Sapphire\FFXIVQuickLauncher\lib\Nhaama\Nhaama.FFXIV\Actor\ActorTableCollection.cs:line 31
   at Nhaama.FFXIV.Game.Update() in E:\Sapphire\FFXIVQuickLauncher\lib\Nhaama\Nhaama.FFXIV\Game.cs:line 47
   at XIVLauncher.Addon.RichPresenceAddon.<DoWork>d__5.MoveNext() in E:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Addon\Implementations\XivRichPresence\RichPresenceAddon.cs:line 60

Last message posted in the server seems to be the same day this error happened.

Perhaps it's been fixed since then. Sorry for bothering.

**Comment by goaaats** [comment]
This issue should not occur anymore with further patches.
