### ISSUE TITLE
System.Exception: Game exited prematurely...?

### ISSUE THREAD

**Issue by RyouFuchiKyou** [goaaats/FFXIVQuickLauncher#152]
System.Exception: Game exited prematurely
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 230
4.6.0.0
cc7e5ba
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True
True
True
True
True
English

[]

**Comment by RyouFuchiKyou** [comment]
Sorry ive never used github before..

**Comment by dustin-lennon** [comment]
Same issue after update

```
System.Exception: Game exited prematurely
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 230
4.5.0.0
86a8532
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True
True
True
False
False
English


[]
```

**Comment by goaaats** [comment]
Let's use https://github.com/goaaats/FFXIVQuickLauncher/issues/153 to track this, thanks for the update
