### ISSUE TITLE
System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by stmikaine** [goaaats/FFXIVQuickLauncher#171]
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 234
4.7.2.0
65be2ff
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True

[]

**Comment by Zyian** [comment]
Can you please use the new Issue format for a bug report, and provide more details? Such as what your settings are, how you got to this error, etc

**Comment by goaaats** [comment]
Pretty sure this is NativeLauncher failing with a hresult, will handle better in the next update
