### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by nKyra** [goaaats/FFXIVQuickLauncher#178]
System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Settings.LauncherSettings.Load() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Settings\LauncherSettings.cs:line 59
   at XIVLauncher.Settings.LauncherSettings.TryMigrate(ILauncherSettingsV3 newSetting) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Settings\LauncherSettings.cs:line 90
   at XIVLauncher.Windows.MainWindow.InitializeWindow() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 139
   at XIVLauncher.App.App_OnStartup(Object sender, StartupEventArgs e) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\App.xaml.cs:line 154
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at XIVLauncher.App.Main()
4.7.3.0
a55b6fb
Context: Unhandled
Microsoft Windows NT 6.2.9200.0
True
False
False
False
False
Japanese

**Comment by Aida-Enna** [comment]
Please fill out some more information below so we can help you out. Thanks!

**Describe the bug here:**
Example: ``I can't play Galaga in the FFXIV Launcher as expected``


**Steps to reproduce the bug:**
Example:
```
1. Click on Settings
2. Click on Auto-Launcher
3. Input the Konami code
4. Nothing happens :(
```


**Expected behavior**
A clear and concise description of what you expected to happen.
Example: ``I expected the game to start when I put in the Konami code``


**Screenshots**
If applicable, add screenshots to help explain your problem.
Example:
![Super cool screenshot](https://i.imgur.com/y99ALui.png)


**Other information (*please* complete the following information):**
  Operating System:
  XIVLauncher version:
  Launching as admin?:
  Using Steam?:
  Addons/Plugins enabled:

**Additional information**
Add any other context about the problem here.

**Comment by nKyra** [comment]
Describe the bug here:
I can't install XIVlauncher

Steps to reproduce the bug:
1. Click on Setup.exe
2. Error happen
Expected behavior
 I expected the setup to start properly.

Screenshots
https://i.imgur.com/EEFB09C.png

Other information (please complete the following information):
Operating System: Windows 10
XIVLauncher version: Version 4.7.3
Launching as admin?: Yes
Using Steam?: Yes
Addons/Plugins enabled:

Additional information
all on 1st comment for the error.

**Comment by goaaats** [comment]
Will be fixed in the next update!

**Comment by ff-meli** [comment]
In the meantime, can you go delete %APPDATA%\XivLauncher\launcherConfig.json?  (%APPDATA% is C:\Users\YourUserName\AppData\Roaming)

You may have to re-enter your account info into the launcher and redo your settings, but that should hopefully only be something you do once ever.

**Comment by nKyra** [comment]
> In the meantime, can you go delete %APPDATA%\XivLauncher\launcherConfig.json? (%APPDATA% is C:\Users\YourUserName\AppData\Roaming)
> 
> Then re-run the launcher setup.
> 
> You may have to re-enter your account info into the launcher and redo your settings, but that should hopefully only be something you do once ever.

oh wow that's actually fixed. Thank you alot !!
