### ISSUE TITLE
System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by stmikaine** [goaaats/FFXIVQuickLauncher#180]
gosh posting here always makes me feel bad but this issue has been so persistent it has annoyed me for a few days now-- i'm not using the steam version & there don't seem to be any issues with its path or any of my other mods or antivirus (i have tried disabling and all of them) but it doesn't seem to treat kindly. im on windows 10!

System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at XIVLauncher.Game.XivGame.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean closeMutants) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 246
4.7.3.0
a55b6fb
Context: XG LaunchGame
Microsoft Windows NT 6.2.9200.0
True

[]

**Comment by goaaats** [comment]
This shouldn't occur anymore as of 4.8.0.0.
