### ISSUE TITLE
dalamud err: could not get swapchain address

### ISSUE THREAD

**Issue by MaxineMutini** [goaaats/FFXIVQuickLauncher#182]
game crashes on startup. ive dived through the logs and found that the game exits directly after `[INF] Started dalamud!`. so i dug around and found the dalamud log files and discovered the following error:
```
[ERR] Could not get SwapChain address via sig method, falling back to vtable...
System.Collections.Generic.KeyNotFoundException: Can't find a signature of 48 8B C4 55 41 54 41 55 41 56 41 57 48 8D 68 ?? 48 81 EC C0 00 00 00
   at Dalamud.Game.SigScanner.Scan(IntPtr baseAddress, Int32 size, String signature)
   at Dalamud.Game.SigScanner.ScanModule(String signature)
   at Dalamud.Game.Internal.DXGI.SwapChainSigResolver.Setup64Bit(SigScanner sig)
   at Dalamud.Game.Internal.BaseAddressResolver.Setup(SigScanner scanner)
   at Dalamud.Interface.InterfaceManager..ctor(Dalamud dalamud, SigScanner scanner)
```
this error was caused by simply logging in. the game window opens up, gets to the "Square Enix" logo, then immediately crashes.

  Operating System: Win10x64 v1909
  XIVLauncher version: xivlauncher-4.7.3.0-a55b6fb
  Launching as admin?: no, doing so gives different errors. if you want those, ill make a new report
  Using Steam?: no
  Addons/Plugins enabled: Rich Presence

**Comment by Aida-Enna** [comment]
Are you sure you're using the latest version of the game? Silly question, I know. Just gotta cover all the bases 😃

**Comment by MaxineMutini** [comment]
i should be, cuz the default launcher boots it with no issues

**Comment by Aida-Enna** [comment]
Can you post the error it gives you when you launch as admin? You can just post it here.

**Comment by MaxineMutini** [comment]
![image](https://user-images.githubusercontent.com/38175382/75835171-07b2c500-5d73-11ea-8441-2f3bb01758c0.png)
![image](https://user-images.githubusercontent.com/38175382/75835234-2618c080-5d73-11ea-9c30-0e3dad1030fd.png)

**Comment by MaxineMutini** [comment]
![image](https://user-images.githubusercontent.com/38175382/75835277-421c6200-5d73-11ea-94e3-a4e35f7e84f2.png)

**Comment by Aida-Enna** [comment]
Try this https://github.com/goaaats/FFXIVQuickLauncher/wiki/FAQ#q-im-getting-a-msvcp140dll-was-not-found-or-vcruntime140dll-was-not-found-issue-help

**Comment by MaxineMutini** [comment]
on it

**Comment by MaxineMutini** [comment]
there are no longer any errors in either log file, but it still crashes

**Comment by Aida-Enna** [comment]
To be clear, when running both as admin and not, the game crashes at the square enix logo with no popup error or anything in the logs?

**Comment by MaxineMutini** [comment]
correct

**Comment by MaxineMutini** [comment]
just tried again as default user and got this error in dalamud.txt
```
[FTL] Unhandled exception on AppDomain
System.NullReferenceException: Object reference not set to an instance of an object.
   at ImGuiScene.RawDX11Scene.Dispose(Boolean disposing) in C:\Users\jonas\Documents\repos\Dalamud\lib\ImGuiScene\ImGuiScene\RawDX11Scene.cs:line 262
   at ImGuiScene.RawDX11Scene.Finalize() in C:\Users\jonas\Documents\repos\Dalamud\lib\ImGuiScene\ImGuiScene\RawDX11Scene.cs:line 281
```

**Comment by MaxineMutini** [comment]
fiddled around with settings and discovered that disabling ingame feature fixes the issue at the cost of the obvious

**Comment by ff-meli** [comment]
A few questions:

- Are you running the dx11 version of the game?  The dx9 one won't work.
- Do you have dxgi.dll, dxgi.fx or d3d11.dll in your game folder? (the same folder that has ffxiv_dx11.exe).  If so, could you delete them and/or uninstall whatever programs added them, and try again?
- Are you running any other things that change game appearance (like reshade/gshade) or add other overlays onto the game?

If none of those seem promising, could you try this?
- Delete the dalamud.txt logfile entirely (from %APPDATA%\XIVLauncher\addon\Hooks\)
- Run the launcher (NOT as admin), ensure in-game features IS enabled, launch the game.
- Assuming that crashes, post the new dalamud.txt logfile here.

Thanks!

**Comment by MaxineMutini** [comment]
[dalamud.txt](https://github.com/goaaats/FFXIVQuickLauncher/files/4285175/dalamud.txt)
no overlays or tuners that i can think of, i even turned off the windows game tuner thing with no luck. the files you mentioned dont exist. deleted the txt file, launched as normal user, and crashed. dalamud log is attached as requested

**Comment by ff-meli** [comment]
Thanks for trying all that.

The only other thing I could think of that is somewhat easy to test is to make sure your graphics drivers are up to date, but I would be surprised if that mattered.

That error is not something I would expect to see on windows, and it's actually more of a warning - things should usually still work anyway, just potentially with some artifacts if you were also using gshade or similar.

I'm not too sure what else I can have you try without a build that has more logging enabled or similar, but it's not easy to get those out to individual people for testing.

Could you find your C:\Windows\System32\dxgi.dll file and upload it here (in a zip etc is fine if it doesn't let you directly)?  I can try testing with that locally to see if there's something different about it, but there really shouldn't be...

**Comment by MaxineMutini** [comment]
[dxgi.zip](https://github.com/goaaats/FFXIVQuickLauncher/files/4285265/dxgi.zip)

**Comment by MaxineMutini** [comment]
im kinda at a loss as well, sorry

**Comment by ff-meli** [comment]
It's ok, this stuff is always a bit weird.  Your dll is identical to mine, so at least that isn't the problem!

I'll add a bunch of logging and see if we can't get you a build to test with to hopefully make it a bit more clear what exactly is breaking.  I'm not sure when exactly that might be though.

**Comment by ff-meli** [comment]
OK - if you are not comfortable doing this for a test, that's perfectly all right, but we'll have to wait for goat to make a test build available in some fashion.  If you don't mind a one-off build that I created for testing, try this:

- Download a test build of the in-game features from my repo [here](https://github.com/ff-meli/Dalamud/releases/download/test1/Hooks.zip)
- Go to %APPDATA%\XivLauncher\addon\
- Delete the entire Hooks folder.  (This is very easy to replace with the real version later)
- Unzip that archive directly into the "addon" folder.  It should create a replacement Hooks folder with everything necessary inside.
- Run XivLauncher.
- Enable in-game features again.
- Launch the game.
- I assume it will crash again, since basically all this does is add some logging.  Even if it doesn't, you don't need to go in game beyond the title screen.
- Upload the new dalamud.txt here.

Sorry for the headache!  I can't really debug this one easily since I can't cause the problem to happen, so I'm hoping this will have some more info.

**Comment by MaxineMutini** [comment]
i have no idea what changed, but its working. im gonna relaunch with default hooks to see if thats it

**Comment by MaxineMutini** [comment]
default hooks crashed the game

**Comment by MaxineMutini** [comment]
theres no log file for the test build, and /xlhelp doesnt work, so im assuming it didnt even boot

**Comment by ff-meli** [comment]
Can you check the output log in %APPDATA%\XivLauncher and see if it has any messages about failing to load?  There's no reason I can think of that it would load automatically if the normal one does.

**Comment by mattavist** [comment]
I’m seeing the exact behavior that MaxineMutini describes, down to in-game features not working with the debug hooks.

The output log does not contain and messages about loading failures.

Happy to help debug or provide other information here.

**Comment by ff-meli** [comment]
Can you look inside the unzipped Hooks folder and see if any or all of .exe files are set as blocked?  (right click, properties, see if there is a message about downloaded things being blocked down near the bottom, along with an 'unblock' option)

I'm not sure why it would just fail to load, especially with no error, when I can dl and unzip that build and it just works...  There are also only very minor changes in that test build, and nothing that is involved with how it is loaded.
