### ISSUE TITLE
Can't even launch the launcher..

### ISSUE THREAD

**Issue by FoxPriestess** [goaaats/FFXIVQuickLauncher#186]
System.AggregateException: One or more errors occurred. ---> System.Exception: Could not get local game version. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\boot\locales\game\ffxivgame.ver'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at XIVLauncher.Game.XivGame.GetLocalGameVer(DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 458
   --- End of inner exception stack trace ---
   at XIVLauncher.Game.XivGame.GetLocalGameVer(DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 462
   at XIVLauncher.Game.XivGame.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 337
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Game.XivGame.Login(String userName, String password, String otp, Boolean isSteamServiceAccount, Boolean useCache, DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 132
   at XIVLauncher.Windows.MainWindow.<StartGame>d__14.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 334
---> (Inner Exception #0) System.Exception: Could not get local game version. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\boot\locales\game\ffxivgame.ver'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at XIVLauncher.Game.XivGame.GetLocalGameVer(DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 458
   --- End of inner exception stack trace ---
   at XIVLauncher.Game.XivGame.GetLocalGameVer(DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 462
   at XIVLauncher.Game.XivGame.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\XivGame.cs:line 337
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

4.7.3.0
a55b6fb
Context: Login
Microsoft Windows NT 6.2.9200.0
True
True
True
True
True
English
C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\boot\locales

[]

**Comment by Aida-Enna** [comment]
Please fill out the following information:

**Describe the bug here:**
Example: ``I can't play Galaga in the FFXIV Launcher as expected``


**Steps to reproduce the bug:**
Example:
```
1. Click on Settings
2. Click on Auto-Launcher
3. Input the Konami code
4. Nothing happens :(
```


**Expected behavior**
A clear and concise description of what you expected to happen.
Example: ``I expected the game to start when I put in the Konami code``


**Screenshots**
If applicable, add screenshots to help explain your problem.
Example:
![Super cool screenshot](https://i.imgur.com/y99ALui.png)


**Other information (*please* complete the following information):**
  Operating System:
  XIVLauncher version:
  Launching as admin?:
  Using Steam?:
  Addons/Plugins enabled:

**Additional information**
Add any other context about the problem here.

**Comment by Aida-Enna** [comment]
Additionally, have you ever played the game before or launched it through the official launcher before using this?

**Comment by goaaats** [comment]
Start the launcher while holding shift and fix your game directory in the settings menu.

**Comment by goaaats** [comment]
This should be disabling AutoLaunch automatically now.
