### ISSUE TITLE
error popped up when multi boxing

### ISSUE THREAD

**Issue by AmenneHolelane** [goaaats/FFXIVQuickLauncher#197]
System.UnauthorizedAccessException: Access to the path 'Dalamud.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.Delete()
   at XIVLauncher.Dalamud.DalamudLauncher.Download(String addonPath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 151
   at XIVLauncher.Dalamud.DalamudLauncher.Run(DirectoryInfo gamePath, ClientLanguage language) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 85
   at XIVLauncher.Windows.MainWindow.<StartGame>d__14.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 427
4.7.3.0
a55b6fb
Context: Hooks
Microsoft Windows NT 6.2.9200.0
True
True
True
False
False
English
C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online

[]

**Comment by AmenneHolelane** [comment]
game still loaded fine, all plugins are functional

**Comment by goaaats** [comment]
This needs a mutex while dalamud is running, so another XL instance can't attempt to update it. Will fix issues with multiple updates happening at the same time as well.

**Comment by goaaats** [comment]
This is fixed with 4.8
