### ISSUE TITLE
error

### ISSUE THREAD

**Issue by HawtSTuff1337** [goaaats/FFXIVQuickLauncher#41]
System.ComponentModel.Win32Exception (0x80004005): The operation was canceled by the user
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at XIVLauncher.MainWindow.StartAddons(Process gameProcess)
   at XIVLauncher.MainWindow.StartGame()
1.8.0.0
7b1d598

**Comment by goaaats** [comment]
That's your antivirus, please check its logs and add exclusions if it found anything

**Comment by goaaats** [comment]
Closing as no response from owner
