### ISSUE TITLE
Rich Presence Access Denied

### ISSUE THREAD

**Issue by babagabrys** [goaaats/FFXIVQuickLauncher#44]
`System.UnauthorizedAccessException: Access to the path 'C:\Users\Nighteyes\AppData\Roaming\XIVLauncher\addon\RichPresence\DiscordRPC.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at XIVLauncher.Addon.RichPresenceAddon.Download(String path)
   at XIVLauncher.Addon.RichPresenceAddon.Run(Process gameProcess)
   at XIVLauncher.MainWindow.StartAddons(Process gameProcess)
   at XIVLauncher.MainWindow.StartGame()
1.8.1.0
8432735
Context: Addons
Microsoft Windows NT 6.2.9200.0
True
True
True
True

[
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": true,
    "Addon": {
      "$type": "XIVLauncher.Addon.RichPresenceAddon, XIVLauncher",
      "Name": "FFXIV Discord Rich Presence"
    }
  }
]
`

followed by error below: 
`System.UnauthorizedAccessException: Access to the path 'C:\Users\Nighteyes\AppData\Roaming\XIVLauncher\addon\Hooks\Dalamud.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at XIVLauncher.Addon.HooksAddon.Download(String path)
   at XIVLauncher.Addon.HooksAddon.Run(Process gameProcess)
   at XIVLauncher.MainWindow.StartGame()
1.8.1.0
8432735
Context: Hooks
Microsoft Windows NT 6.2.9200.0
True
True
True
True

[
  {
    "$type": "XIVLauncher.Addon.AddonEntry, XIVLauncher",
    "IsEnabled": true,
    "Addon": {
      "$type": "XIVLauncher.Addon.RichPresenceAddon, XIVLauncher",
      "Name": "FFXIV Discord Rich Presence"
    }
  }
]
`

**Comment by babagabrys** [comment]
update - fixed by extracting the folders called "download" in the appdata folder - may be worth adding to your FAQ - had some issues with folder being not owned by me but this can be resolved with a quick google and restart
